CREATE TABLE USUARIO (
	ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    SENHA VARCHAR(12) NOT NULL
);

CREATE TABLE CURSO (
	ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(100) NOT NULL
);



CREATE TABLE TOPICO (
	ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL,
    MENSAGEM TEXT NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    AUTOR_ID BIGINT NOT NULL,
    CURSO_ID INT NOT NULL
);








